version: "3"
services:
  postgres:
    image: library/postgres:12.0
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: eshop
      POSTGRES_DB: Identification
#    restart: unless-stopped
  springbootapp:
    container_name: identification-server
    build: ./
    user: root
    command: sh -c "./gradlew clean && ./gradlew build && java -jar ./build/libs/identification-0.0.1-SNAPSHOT.jar"
    ports:
      - "9090:9090"
    depends_on:
      - postgres
volumes:
  postgres-data: