apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: springbootapp
  name: springbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: springbootapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: springbootapp
    spec:
      containers:
      - args:
        - sh
        - -c
        - java -jar ./build/libs/identification-0.1.0.jar
        image: springbootapp
        imagePullPolicy: ""
        name: identification-server
        ports:
        - containerPort: 9090
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
